### ISSUE TITLE
Unmask feature

### ISSUE THREAD

**Issue by jushii** [mob-sakai/MeshEffectForTextMeshPro#2]
Have you considered adding unmask support for TextMeshPro?

Similar like in this repository https://github.com/mob-sakai/UnmaskForUGUI

**Comment by mob-sakai** [comment]
Hi @jushii 

Yes.
After some experiments, I will implement it ;)

**Comment by mob-sakai** [comment]
Congratulations 🎉 
Fortunately, UnmaskForUGUI works well with TextMeshProUGUI :)

I tested it as follows:
1. Import UnmaskForUGUI
2. Open "Unmask_Demo" scene
3. Select "Canvas/Start/Unmask - Text" game object
4. Delete Text component and add TextMeshProUGUI component
5. It works well 👍 

![](https://user-images.githubusercontent.com/12690315/49934872-e3bb5780-ff12-11e8-8803-28dc4d936f87.png)

**Comment by jushii** [comment]
Great to hear! I will try it out soon.
